### ISSUE TITLE
spt_input form-control classes is not resizable to the right

### ISSUE THREAD

**Issue by listyque** [Southpaw-TACTIC/TACTIC#1435]
When i want to resize my edit it allows resizing only in one direction

**Comment by remkonoteboom** [comment]
It turns out that this is a default setting for Bootstrap Material Design.  It has the following css:
resize: vertical
Turning this off site wide produces some bizarre behavior on forms.  I have turned it on explicitly on inline edit of tables for now.  Now that I know why the restriction is there, we can find places where it would be beneficial to have resizing both directions.  I am a little reluctant to turn it on sitewide at the moment as the restriction is likely there for a reason.  We can turn on horizontal resizing in specific places for now.

**Comment by remkonoteboom** [comment]
This behavior turns out to be quite common.  Actually, if you try it out on this text field on Github, the same behavior is exhibited.  I think they are trying to prevent resizing the text area to mess up the structure of the page, so it would only make sense in certain cases.  Thus, the current behavior of horizontal scrolling should be the default and if there are location that it should not be this, we should create a specific issue for that case.  This will allow me to close this issue and not have it lingering around forever.
