### ISSUE TITLE
Admin >> link overlap other UI's

### ISSUE THREAD

**Issue by listyque** [Southpaw-TACTIC/TACTIC#1445]
May be it should not overlap, but be in their own place? Also it has cursor for text editing instead hand cursor.

**Comment by remkonoteboom** [comment]
The reason the Admin bar is an overlay to the UI is because it does not interfere with height calculation for css calc functions to produce a single page app.  This is not a problem for apps that use a main scrollbar.  I suppose we could have a project setting that could set this or maybe a config in the TACTIC conf file?

**Comment by listyque** [comment]
This is not so annoying i think. I just prefer the old style that was in 4.5, where admin link taken his own space, and feed it when closed.

**Comment by remkonoteboom** [comment]
This can no be set to to be in a relative position with project setting.

"admin/bar_position" set to "relative".  By default it is "fixed".

**Comment by listyque** [comment]
> admin/bar_position

How to apply this to ALL projects?
