### ISSUE TITLE
Server Error: Command key not valid (Worflow Editor 4.8)

### ISSUE THREAD

**Issue by listyque** [Southpaw-TACTIC/TACTIC#1463]
**Describe the bug**
On the VFX Plugin, when i select any node in Workflow Editor i got the message in title.
Console output:
Error
    at Object.spt.alert (utility.js?ver=4.8.0.b01:1362)
    at wdg_kwargs.on_error (panel.js?ver=4.8.0.b01:174)
    at err_callback (client_api.js?ver=4.8.0.b01:1914)
    at TacticServerStub.async_callback (client_api.js?ver=4.8.0.b01:2124)
    at client_api.js?ver=4.8.0.b01:2070
    at XMLHttpRequest.self.xmlHttpRequest.onreadystatechange (xmlrpc.js?ver=4.8.0.b01:110)

**To Reproduce**
1. Go to Workflow Editor of VFX Plugin
2. Select Shot or Asset pipeline
3. Save the pipeline
4. Click on any Node or i button.

**Expected behavior**
Config toolbar will apear. Without any warning.

**Comment by remkonoteboom** [comment]
Does it still do this even after you full refresh the application?

**Comment by remkonoteboom** [comment]
The reason I ask this is because I can't seem to reproduce your conditions.

**Comment by listyque** [comment]
After refreshing the app and restart server i can't reproduce this error too.

**Comment by remkonoteboom** [comment]
The command key will expire with the login ticket, however, you're UI still referenced this expired command key.  I am not sure this could come about, but since this is pretty new code, there may be some fringe cases where it's not 100%.  I haven't seen any real issues with the command key in a while as it has become pretty stable.  If you find any more problems with it, you can log another issue.
