### ISSUE TITLE
Calendar Widget overlaps Ui

### ISSUE THREAD

**Issue by listyque** [Southpaw-TACTIC/TACTIC#1490]
**Describe the bug**
In the insertion or Edit SObject (tasks edit for exmpla) calendar widget lying behind ui, so it is impossible to use it.

**To Reproduce**
1. Go to Tasks table
2. Click on add new Task
3. Click on Bid Start or Bid End day
4. See Calendar overlapped by other UI elemts

**Expected behavior**
Calendar over other widgets

**Comment by remkonoteboom** [comment]
I have made it so that CalendarInputWdg now uses the browser input for dates.  They are now good enough and standard enough that it deprecates the built-in TACTIC one.  The TACTIC one is still available with the "edit_mode" option, if for some reason you still want the TACTIC one.

The TACTIC one is still in the DOM and as such is subject to "overflow: hidden".  If we do keep the TACTIC one around for whatever reason, then we should keep the calendar in a global DOM space and position accordingly.  However, this work won't be necessary if the browser calendar input completely replaces it.
