### ISSUE TITLE
Relationship [general] not supported yet

### ISSUE THREAD

**Issue by listyque** [Southpaw-TACTIC/TACTIC#1492]
**Describe the bug**
In a VFX template/plugin there is a relationship named general. But when i try to add relationship_filter to vfx/art_reference i got this error. 
```
<connect to="*" type="connection" from="vfx/art_reference" relationship="general"/>
```
**To Reproduce**
```
sobjects_list = list of vfx/art_reference SObjects

search = Search('sthpw/snapshot')
search .add_relationship_filters(sobjects_list, op='in')
```

**Expected behavior**
List of related snapshots SObjects

**Comment by remkonoteboom** [comment]
The "connect" relationship is a relationship entity that can connect two arbitrary sobjects even between two projects.  It was developed but never really used and it complicates things because the connection table is in the sthpw database.  It may be more useful in the project table and only allow relationships between entities within a project.

However, I think this line was left over from testing and made it into a commit.  At present, I think it is best to remove this line from the schema until there is better support for this connection stype.
