### ISSUE TITLE
Changing the width of the table columns is really buggy.

### ISSUE THREAD

**Issue by listyque** [Southpaw-TACTIC/TACTIC#1660]
**Describe the bug**
When someone tries to adjust columns widths all the columns looses their "resize logic"

**To Reproduce**
1. Open any table with multiple columns
2. Try to adjust widths of the columns
3. See the glitches

**Expected behavior**
Predictable behavior when columns widths being resized

**Screenshots**
![sSRs7XUV2q](https://user-images.githubusercontent.com/13370598/124475482-70b4ad80-ddaa-11eb-9cc8-3cfbbd546546.gif)

**Comment by remkonoteboom** [comment]
As I mentioned in the forum, this is primarily due to use of html <tables>.  I have started prototyping the use of <div>.  It turns out tables are fundamentally ill suited for this kind of flexibility.  I think we took it as far as we could go and only a switch over to the use of <div> will these be resolved.  This will take a bit of work, but after some prototyping, I don't think it will be that much work.

**Comment by listyque** [comment]
As we can see, all tables in the Material examples are flexible, and auto adjustable. I don't know, may be some rows can be made automatic, and others could be adjustable by user.
Anyway, I was trying to look how tables in tactic work, and wanted to make its content centered in cells and rows, then I found it is made at the highest level, out of my understanding of web techs...

Well, i think this issue can be closed?

**Comment by remkonoteboom** [comment]
No, keep it open.  

I am working on converting the TableLayoutWdg from using table, tr, td tags to using div tags.  This solves a lot of display problems, including the resizing of columns.  <table> tags just do not behave predictably when setting their sizes.  We were able to work around many of the issues, but could never completely stamp out issues.  And any change would cause things to break as in your video above.

I have to be careful because so much uses this class, but initial results are promising.  The display is much more predictable.  However, there are a bunch of minor display issues because the whole paradigm has changed.
